/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/PerfumeEffectManager")]
    [LuaRegisterType(0x85236f5062439ffd, typeof(LuaBehaviour))]
    public class PerfumeEffectManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "6f460fb9d95d74e00aaee278f21dc4be";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_perfumeEffect1 = default;
        [SerializeField] public UnityEngine.GameObject m_perfumeEffect2 = default;
        [SerializeField] public UnityEngine.GameObject m_perfumeEffect3 = default;
        [SerializeField] public UnityEngine.GameObject m_perfumeEffect4 = default;
        [SerializeField] public UnityEngine.GameObject m_perfumeEffect5 = default;
        [SerializeField] public UnityEngine.GameObject m_sparkleEffect = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_perfumeEffect1),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_perfumeEffect2),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_perfumeEffect3),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_perfumeEffect4),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_perfumeEffect5),
                CreateSerializedProperty(_script.GetPropertyAt(5), m_sparkleEffect),
            };
        }
    }
}

#endif
