/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/Perfume")]
    [LuaRegisterType(0xe1ea00899b3882eb, typeof(LuaBehaviour))]
    public class Perfume : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "d1315811afa2d410d97980f9158b8fe6";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_perfumeSprayObject = default;
        [SerializeField] public System.String m_effectKey = "floral";

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_perfumeSprayObject),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_effectKey),
            };
        }
    }
}

#endif
